[package]
name = "commits-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "commits"
path = "src/main.rs"

[dependencies]
bones-messages = { path = "../vendor/bones/shared/bones-messages" }
bus = { path = "../vendor/bones/core/bus" }
commits-git = { path = "../modules/git" }
commits-os = { path = "../modules/os" }
commits-watcher = { path = "../modules/watcher" }
logging = { path = "../vendor/bones/core/logging" }
runner = { path = "../vendor/bones/core/runner", features = ["web"] }
wasm-extensions = { path = "../vendor/bones/core/wasm-extensions" }

