import { mkdir, readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const script = await readFile(new URL("dist/ui/page.js", root), "utf8");
const css = await readFile(new URL("ui/src/main.css", root), "utf8");
const template = await readFile(new URL("ui/src/index.html", root), "utf8");
const html = template
  .replace("/*__COMMITS_CSS__*/", css)
  .replace("/*__COMMITS_JS__*/", script);
const previewIpc = `
window.ipc = { postMessage(json) {
  const request = JSON.parse(json);
  const response = request.command === "pageReady"
    ? { command: "coreReady", runtime: "bones" }
    : { ...request, receivedAt: new Date().toISOString() };
  queueMicrotask(() => window.dispatchEvent(
    new CustomEvent("bones-message", { detail: JSON.stringify(response) })
  ));
} };`;
const preview = template
  .replace("/*__COMMITS_CSS__*/", css)
  .replace("/*__COMMITS_JS__*/", `${previewIpc}\n${script}`);
const target = new URL("core/src/generated/page.ts", root);

await mkdir(new URL("core/src/generated/", root), { recursive: true });
await writeFile(new URL("dist/ui/preview.html", root), preview);
await writeFile(
  target,
  `// Generated by scripts/generate-page.mjs.\nexport const pageHtml = ${JSON.stringify(html)};\n`,
);
